version: "3.8"

services:
    db:
        image: postgres:13
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

    server:
        build: .
        command: sh -c "npm install && npm run dev"
        volumes:
            - .:/app
            - /app/node_modules
            - /.env
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file:
            - .env

volumes:
    db-data:
